$CLS
PROMPT Menu:
PROMPT 1. CREATE TABLES
PROMPT 2. DROP TABLES
PROMPT 3. INSERT INTO TABLES
PROMPT 4. DELETE FROM TABLES
PROMPT 5. SELECT FROM TABLES
PROMPT 6. CREATE SEQUENCES
PROMPT 7. DROP SEQUENCES
PROMPT 8. CREATE FUNTIONS AND PROCEDURES
PROMPT 9. DROP FUNTIONS AND PROCEDURES
PROMPT A. EXEC FUNCTIONS
PROMPT B. EXEC PROCEDURES
PROMPT C. Dowolna instrukcja
PROMPT D. Stworz tabele do triggerow
PROMPT E. Usun tabele do triggerow
PROMPT F. Stworz triggery
PROMPT g. Usun triggery
PROMPT 0. KONIEC
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT '?: '
$CLS
PROMPT wybor = &wybor
@&wybor\main.sql &wybor
PROMPT 
PROMPT # Wcisnij ENTER #
PAUSE
@main.sql